"""Inventory Domain Schemas."""

from app.modules.inventory.schemas.category import (
    CategoryBase,
    CategoryCreate,
    CategoryListResponse,
    CategoryResponse,
    CategoryUpdate,
)
from app.modules.inventory.schemas.goods_receipt import (
    GoodsReceiptBase,
    GoodsReceiptCreate,
    GoodsReceiptItemBase,
    GoodsReceiptItemCreate,
    GoodsReceiptItemResponse,
    GoodsReceiptListResponse,
    GoodsReceiptResponse,
    GoodsReceiptUpdate,
)
from app.modules.inventory.schemas.product import (
    ProductBase,
    ProductCreate,
    ProductListResponse,
    ProductResponse,
    ProductUpdate,
)
from app.modules.inventory.schemas.stock_adjustment import (
    StockAdjustmentBase,
    StockAdjustmentCreate,
    StockAdjustmentItemBase,
    StockAdjustmentItemCreate,
    StockAdjustmentItemResponse,
    StockAdjustmentListResponse,
    StockAdjustmentResponse,
    StockAdjustmentUpdate,
)
from app.modules.inventory.schemas.stock_balance import (
    StockBalanceListResponse,
    StockBalanceResponse,
    StockValuationSummary,
)
from app.modules.inventory.schemas.stock_movement import (
    StockMovementCreate,
    StockMovementListResponse,
    StockMovementResponse,
)
from app.modules.inventory.schemas.stock_transfer import (
    StockTransferBase,
    StockTransferCreate,
    StockTransferItemBase,
    StockTransferItemCreate,
    StockTransferItemResponse,
    StockTransferListResponse,
    StockTransferResponse,
    StockTransferUpdate,
)
from app.modules.inventory.schemas.uom import (
    UomBase,
    UomCreate,
    UomListResponse,
    UomResponse,
    UomUpdate,
)
from app.modules.inventory.schemas.warehouse import (
    LocationBase,
    LocationCreate,
    LocationResponse,
    LocationUpdate,
    WarehouseBase,
    WarehouseCreate,
    WarehouseListResponse,
    WarehouseResponse,
    WarehouseUpdate,
)

__all__ = [
    "UomBase",
    "UomCreate",
    "UomUpdate",
    "UomResponse",
    "UomListResponse",
    "CategoryBase",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "CategoryListResponse",
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductListResponse",
    "LocationBase",
    "LocationCreate",
    "LocationUpdate",
    "LocationResponse",
    "WarehouseBase",
    "WarehouseCreate",
    "WarehouseUpdate",
    "WarehouseResponse",
    "WarehouseListResponse",
    "StockBalanceResponse",
    "StockBalanceListResponse",
    "StockValuationSummary",
    "StockMovementCreate",
    "StockMovementResponse",
    "StockMovementListResponse",
    "StockTransferBase",
    "StockTransferCreate",
    "StockTransferUpdate",
    "StockTransferResponse",
    "StockTransferListResponse",
    "StockTransferItemBase",
    "StockTransferItemCreate",
    "StockTransferItemResponse",
    "StockAdjustmentBase",
    "StockAdjustmentCreate",
    "StockAdjustmentUpdate",
    "StockAdjustmentResponse",
    "StockAdjustmentListResponse",
    "StockAdjustmentItemBase",
    "StockAdjustmentItemCreate",
    "StockAdjustmentItemResponse",
    "GoodsReceiptBase",
    "GoodsReceiptCreate",
    "GoodsReceiptUpdate",
    "GoodsReceiptResponse",
    "GoodsReceiptListResponse",
    "GoodsReceiptItemBase",
    "GoodsReceiptItemCreate",
    "GoodsReceiptItemResponse",
]
