"""Centralized registration of all SQLAlchemy ORM models."""

from app.infrastructure.database.base import Base, BaseEntity
from app.modules.ai.models import (
    AIConversation,
    AIMessage,
    AIToolExecution,
    AIUsageLog,
    RAGDocument,
    RAGDocumentChunk,
    RAGDocumentVersion,
    RAGIngestionJob,
)
from app.modules.analytics.models import (
    AnalyticsReport,
    Dashboard,
    DashboardWidget,
    KPIDefinition,
    KPISnapshot,
    ReportExecution,
)
from app.modules.audit.models.audit_entry import AuditLogEntry, SecurityEventLog
from app.modules.crm.models import (
    Activity,
    Contact,
    Customer,
    Deal,
    DealStageHistory,
    Lead,
    Note,
    Pipeline,
    PipelineStage,
    Quotation,
    QuotationItem,
    SalesOrder,
    SalesOrderItem,
    Task,
)
from app.modules.finance.models import (
    Account,
    BankAccount,
    BankTransaction,
    Bill,
    BillLine,
    CustomerParty,
    FiscalPeriod,
    FiscalYear,
    GeneralLedger,
    Invoice,
    InvoiceLine,
    JournalEntry,
    JournalLine,
    Payment,
    PaymentAllocation,
    VendorParty,
)
from app.modules.hr.models import (
    AttendanceRecord,
    AttendanceRegularization,
    CourseEnrollment,
    CourseModule,
    Employee,
    EmployeeAddress,
    EmployeeBankAccount,
    EmployeeCertification,
    EmployeeDocument,
    EmployeeEmergencyContact,
    EmployeeGoal,
    EmployeeLifecycleEvent,
    EmployeeProfile,
    EmployeeSalaryAssignment,
    EmployeeSkill,
    EmploymentContract,
    InterviewFeedback,
    InterviewSchedule,
    JobApplicant,
    JobOffer,
    JobRequisition,
    LeaveBalance,
    LeavePolicy,
    LeaveRequest,
    LeaveType,
    OnboardingTask,
    PayrollRun,
    Payslip,
    PayslipLine,
    PerformanceReview,
    PerformanceReviewPeriod,
    SalaryComponent,
    SalaryStructure,
    SalaryStructureItem,
    Shift,
    ShiftAssignment,
    TrainingCourse,
)
from app.modules.identity.models.mfa_setting import ApiKey, MfaSetting
from app.modules.identity.models.role import Permission, Role, RolePermission, UserRole
from app.modules.identity.models.user import User
from app.modules.identity.models.user_credential import UserCredential, UserSession
from app.modules.inventory.models import (
    GoodsReceipt,
    GoodsReceiptItem,
    Location,
    Product,
    ProductCategory,
    StockAdjustment,
    StockAdjustmentItem,
    StockBalance,
    StockMovement,
    StockTransfer,
    StockTransferItem,
    UnitOfMeasure,
    Warehouse,
)
from app.modules.jobs.models import (
    BackgroundJob,
    JobExecutionLog,
    JobSchedule,
)
from app.modules.manufacturing.models import (
    BillOfMaterial,
    BOMComponent,
    BOMVersion,
    Machine,
    MaterialConsumption,
    MRPPlannedOrder,
    MRPRun,
    ProductionOrder,
    ProductionOutput,
    ProductionScrap,
    QualityInspection,
    Routing,
    RoutingOperation,
    WorkCenter,
    WorkOrder,
)
from app.modules.organization.models.branch import Branch
from app.modules.organization.models.business_unit import BusinessUnit
from app.modules.organization.models.calendar import WorkCalendar, WorkingDay
from app.modules.organization.models.cost_center import CostCenter
from app.modules.organization.models.department import Department
from app.modules.organization.models.designation import Designation
from app.modules.organization.models.holiday import Holiday
from app.modules.organization.models.location import Location as OrgLocation
from app.modules.organization.models.organization import Organization, TenantMembership
from app.modules.organization.models.team import Team, TeamMember
from app.modules.organization.models.tenant import Tenant
from app.modules.procurement.models import (
    PurchaseOrder,
    PurchaseOrderItem,
    PurchaseRequest,
    PurchaseRequestItem,
    Supplier,
)

__all__ = [
    "Base",
    "BaseEntity",
    "Tenant",
    "Organization",
    "TenantMembership",
    "Branch",
    "Department",
    "Team",
    "TeamMember",
    "Designation",
    "BusinessUnit",
    "CostCenter",
    "OrgLocation",
    "WorkCalendar",
    "WorkingDay",
    "Holiday",
    "User",
    "UserCredential",
    "UserSession",
    "Role",
    "Permission",
    "RolePermission",
    "UserRole",
    "MfaSetting",
    "ApiKey",
    "AuditLogEntry",
    "SecurityEventLog",
    "Employee",
    "EmployeeProfile",
    "EmployeeEmergencyContact",
    "EmployeeAddress",
    "EmployeeBankAccount",
    "EmployeeDocument",
    "EmploymentContract",
    "EmployeeLifecycleEvent",
    "OnboardingTask",
    "Shift",
    "ShiftAssignment",
    "AttendanceRecord",
    "AttendanceRegularization",
    "LeaveType",
    "LeavePolicy",
    "LeaveBalance",
    "LeaveRequest",
    "SalaryComponent",
    "SalaryStructure",
    "SalaryStructureItem",
    "EmployeeSalaryAssignment",
    "PayrollRun",
    "Payslip",
    "PayslipLine",
    "JobRequisition",
    "JobApplicant",
    "InterviewSchedule",
    "InterviewFeedback",
    "JobOffer",
    "PerformanceReviewPeriod",
    "EmployeeGoal",
    "PerformanceReview",
    "TrainingCourse",
    "CourseModule",
    "CourseEnrollment",
    "EmployeeSkill",
    "EmployeeCertification",
    "Lead",
    "Customer",
    "Contact",
    "Pipeline",
    "PipelineStage",
    "Deal",
    "DealStageHistory",
    "Quotation",
    "QuotationItem",
    "SalesOrder",
    "SalesOrderItem",
    "Activity",
    "Note",
    "Task",
    "UnitOfMeasure",
    "ProductCategory",
    "Product",
    "Warehouse",
    "Location",
    "StockBalance",
    "StockMovement",
    "StockTransfer",
    "StockTransferItem",
    "StockAdjustment",
    "StockAdjustmentItem",
    "GoodsReceipt",
    "GoodsReceiptItem",
    "Supplier",
    "PurchaseRequest",
    "PurchaseRequestItem",
    "PurchaseOrder",
    "PurchaseOrderItem",
    "Account",
    "BankAccount",
    "BankTransaction",
    "Bill",
    "BillLine",
    "CustomerParty",
    "FiscalPeriod",
    "FiscalYear",
    "GeneralLedger",
    "Invoice",
    "InvoiceLine",
    "JournalEntry",
    "JournalLine",
    "Payment",
    "PaymentAllocation",
    "VendorParty",
    "WorkCenter",
    "Machine",
    "Routing",
    "RoutingOperation",
    "BillOfMaterial",
    "BOMVersion",
    "BOMComponent",
    "ProductionOrder",
    "WorkOrder",
    "MaterialConsumption",
    "ProductionOutput",
    "ProductionScrap",
    "QualityInspection",
    "MRPRun",
    "MRPPlannedOrder",
    "AnalyticsReport",
    "Dashboard",
    "DashboardWidget",
    "KPIDefinition",
    "KPISnapshot",
    "ReportExecution",
    "AIConversation",
    "AIMessage",
    "AIToolExecution",
    "AIUsageLog",
    "RAGDocument",
    "RAGDocumentVersion",
    "RAGDocumentChunk",
    "RAGIngestionJob",
    "BackgroundJob",
    "JobExecutionLog",
    "JobSchedule",
]
