apiVersion: v1
kind: ServiceAccount
metadata:
  name: vertexerp-api-sa
  namespace: vertexerp-production
  labels:
    app.kubernetes.io/name: vertexerp
    app.kubernetes.io/component: api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vertexerp-worker-sa
  namespace: vertexerp-production
  labels:
    app.kubernetes.io/name: vertexerp
    app.kubernetes.io/component: worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vertexerp-frontend-sa
  namespace: vertexerp-production
  labels:
    app.kubernetes.io/name: vertexerp
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vertexerp-migration-sa
  namespace: vertexerp-production
  labels:
    app.kubernetes.io/name: vertexerp
    app.kubernetes.io/component: migration
automountServiceAccountToken: false
