import logging
from datetime import UTC, datetime

from fastapi import FastAPI, Request, status
from fastapi.encoders import jsonable_encoder
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException

from app.core.exceptions import BaseException as AppBaseException

logger = logging.getLogger(__name__)


def _get_cors_headers(request: Request) -> dict[str, str]:
    """Ensures error responses generated by exception handlers explicitly include CORS headers."""
    origin = request.headers.get("origin")
    if origin:
        return {
            "Access-Control-Allow-Origin": origin,
            "Access-Control-Allow-Credentials": "true",
            "Access-Control-Allow-Methods": "*",
            "Access-Control-Allow-Headers": "*",
        }
    return {
        "Access-Control-Allow-Origin": "*",
    }


def setup_exception_handlers(app: FastAPI) -> None:
    """Configures global error interceptors for the FastAPI app to ensure standard responses."""

    @app.exception_handler(AppBaseException)
    async def app_exception_handler(request: Request, exc: AppBaseException):
        """Intercepts custom application exceptions and formats standard error response."""
        logger.warning(
            f"Application error occurred on {request.url.path}: {exc.message}"
        )

        meta = (
            exc.details
            if isinstance(exc.details, dict)
            else {"details": exc.details} if exc.details else {}
        )

        return JSONResponse(
            status_code=exc.status_code,
            headers=_get_cors_headers(request),
            content=jsonable_encoder(
                {
                    "success": False,
                    "message": exc.message,
                    "data": None,
                    "meta": meta,
                    "timestamp": datetime.now(UTC).isoformat(),
                }
            ),
        )

    @app.exception_handler(StarletteHTTPException)
    async def http_exception_handler(request: Request, exc: StarletteHTTPException):
        """Intercepts Starlette/FastAPI HTTPExceptions and formats standard error response."""
        logger.warning(f"HTTP error occurred on {request.url.path}: {exc.detail}")

        message = (
            exc.detail if isinstance(exc.detail, str) else "HTTP exception occurred"
        )
        meta = exc.detail if isinstance(exc.detail, dict) else {}

        return JSONResponse(
            status_code=exc.status_code,
            headers=_get_cors_headers(request),
            content=jsonable_encoder(
                {
                    "success": False,
                    "message": message,
                    "data": None,
                    "meta": meta,
                    "timestamp": datetime.now(UTC).isoformat(),
                }
            ),
        )

    @app.exception_handler(RequestValidationError)
    async def validation_exception_handler(
        request: Request, exc: RequestValidationError
    ):
        """Intercepts Pydantic/FastAPI model validation errors."""
        logger.error(f"Validation error on {request.url.path}: {exc.errors()}")
        return JSONResponse(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            headers=_get_cors_headers(request),
            content=jsonable_encoder(
                {
                    "success": False,
                    "message": "Validation failed for request parameters",
                    "data": None,
                    "meta": {"errors": exc.errors()},
                    "timestamp": datetime.now(UTC).isoformat(),
                }
            ),
        )

    @app.exception_handler(Exception)
    async def generic_exception_handler(request: Request, exc: Exception):
        """Catch-all handler for unhandled internal code errors (500)."""
        logger.exception(f"Unhandled system error occurred on {request.url.path}")

        meta = {}
        if settings_is_dev():
            import traceback

            meta = {"details": str(exc), "traceback": traceback.format_exc()}

        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            headers=_get_cors_headers(request),
            content=jsonable_encoder(
                {
                    "success": False,
                    "message": "An internal system error occurred. Please contact support.",
                    "data": None,
                    "meta": meta,
                    "timestamp": datetime.now(UTC).isoformat(),
                }
            ),
        )


def settings_is_dev() -> bool:
    """Helper to check if settings is loaded and is in development environment."""
    try:
        from app.core.config import settings

        return settings.ENVIRONMENT == "development"
    except Exception:
        return True
